---
# tasks file for oracle-virtualbox
- apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc
  become: yes
  when: ansible_distribution_release == 'xenial'

- apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc
  become: yes
  when: ansible_distribution_release != 'xenial'

- apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
  become: yes

- apt: name=virtualbox-5.0 update_cache=yes cache_valid_time=300
  become: yes
